# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pind My Way iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pind-My-Way-Map
  pod "GoogleMaps"
  pod "GooglePlaces"
  pod 'SwiftyJSON', '~> 4.0'

end
