# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Pind My Way iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pind-My-Way-Map
  pod "GoogleMaps"
  pod "GooglePlaces"
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Polyline', '~> 4.0'
  pod 'SwiftyXML', '~> 1.7.0'
end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-Pind My Way iOS/Pods-Pind My Way iOS-acknowledgements.plist', 'Pind My Way iOS/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
